# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/FPGA/VHDL/Lab Training/I2C/I2C00 - OV7670 Image/I2C00 - OV7670 Image.srcs/sources_1/bd/top/ip/top_blk_mem_gen_0_0/top_blk_mem_gen_0_0.xci
# IP: The module: 'top_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/VHDL/Lab Training/I2C/I2C00 - OV7670 Image/I2C00 - OV7670 Image.gen/sources_1/bd/top/ip/top_blk_mem_gen_0_0/top_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/FPGA/VHDL/Lab Training/I2C/I2C00 - OV7670 Image/I2C00 - OV7670 Image.srcs/sources_1/bd/top/ip/top_blk_mem_gen_0_0/top_blk_mem_gen_0_0.xci
# IP: The module: 'top_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/VHDL/Lab Training/I2C/I2C00 - OV7670 Image/I2C00 - OV7670 Image.gen/sources_1/bd/top/ip/top_blk_mem_gen_0_0/top_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
