# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/FPGA/VHDL/Lab Training/I2C/I2C01/I2C01.srcs/sources_1/bd/top/ip/top_ila_0_3/top_ila_0_3.xci
# IP: The module: 'top_ila_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/VHDL/Lab Training/I2C/I2C01/I2C01.gen/sources_1/bd/top/ip/top_ila_0_3/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA/VHDL/Lab Training/I2C/I2C01/I2C01.gen/sources_1/bd/top/ip/top_ila_0_3/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA/VHDL/Lab Training/I2C/I2C01/I2C01.gen/sources_1/bd/top/ip/top_ila_0_3/top_ila_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/FPGA/VHDL/Lab Training/I2C/I2C01/I2C01.srcs/sources_1/bd/top/ip/top_ila_0_3/top_ila_0_3.xci
# IP: The module: 'top_ila_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/VHDL/Lab Training/I2C/I2C01/I2C01.gen/sources_1/bd/top/ip/top_ila_0_3/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA/VHDL/Lab Training/I2C/I2C01/I2C01.gen/sources_1/bd/top/ip/top_ila_0_3/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA/VHDL/Lab Training/I2C/I2C01/I2C01.gen/sources_1/bd/top/ip/top_ila_0_3/top_ila_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
