# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Basys3_Master_OV7670.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_clk_wiz_0_0 || ORIG_REF_NAME==top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/top/ip/top_debouncer_0_0/top_debouncer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_debouncer_0_0 || ORIG_REF_NAME==top_debouncer_0_0} -quiet] -quiet

# IP: bd/top/ip/top_I2C_OV7670_Master_0_0/top_I2C_OV7670_Master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_I2C_OV7670_Master_0_0 || ORIG_REF_NAME==top_I2C_OV7670_Master_0_0} -quiet] -quiet

# IP: bd/top/ip/top_ila_0_0/top_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ila_0_0 || ORIG_REF_NAME==top_ila_0_0} -quiet] -quiet

# IP: bd/top/ip/top_I2C_OV7670_config_0_0/top_I2C_OV7670_config_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_I2C_OV7670_config_0_0 || ORIG_REF_NAME==top_I2C_OV7670_config_0_0} -quiet] -quiet

# XDC: e:/FPGA/VHDL/Lab Training/I2C/I2C00 - Basic Communication/I2C00 - Basic Communication.gen/sources_1/bd/top/top_ooc.xdc
