# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Basys3_Master.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_clk_wiz_0_0 || ORIG_REF_NAME==top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/top/ip/top_blk_mem_gen_0_0/top_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_blk_mem_gen_0_0 || ORIG_REF_NAME==top_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/top/ip/top_image_threshold_0_0/top_image_threshold_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_image_threshold_0_0 || ORIG_REF_NAME==top_image_threshold_0_0} -quiet] -quiet

# IP: bd/top/ip/top_blk_mem_gen_1_0/top_blk_mem_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_blk_mem_gen_1_0 || ORIG_REF_NAME==top_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_clk_wiz_0_100M_0/top_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==top_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_0_0/top_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_0_0 || ORIG_REF_NAME==top_xlconstant_0_0} -quiet] -quiet

# IP: bd/top/ip/top_sobel_processor_0_0/top_sobel_processor_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_sobel_processor_0_0 || ORIG_REF_NAME==top_sobel_processor_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_2_0/top_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_2_0 || ORIG_REF_NAME==top_xlconstant_2_0} -quiet] -quiet

# IP: bd/top/ip/top_blk_mem_gen_2_0/top_blk_mem_gen_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_blk_mem_gen_2_0 || ORIG_REF_NAME==top_blk_mem_gen_2_0} -quiet] -quiet

# IP: bd/top/ip/top_UART_TX_CTRL_0_0/top_UART_TX_CTRL_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_UART_TX_CTRL_0_0 || ORIG_REF_NAME==top_UART_TX_CTRL_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_1_0/top_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_1_0 || ORIG_REF_NAME==top_xlconstant_1_0} -quiet] -quiet

# IP: bd/top/ip/top_uart_bram_loader_0_1/top_uart_bram_loader_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_uart_bram_loader_0_1 || ORIG_REF_NAME==top_uart_bram_loader_0_1} -quiet] -quiet

# IP: bd/top/ip/top_ila_0_0/top_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ila_0_0 || ORIG_REF_NAME==top_ila_0_0} -quiet] -quiet

# IP: bd/top/ip/top_line_buffer_simple_0_0/top_line_buffer_simple_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_line_buffer_simple_0_0 || ORIG_REF_NAME==top_line_buffer_simple_0_0} -quiet] -quiet

# IP: bd/top/ip/top_bram_reader_0_1/top_bram_reader_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bram_reader_0_1 || ORIG_REF_NAME==top_bram_reader_0_1} -quiet] -quiet

# XDC: c:/Users/Dev/Documents/vivado test/WYWM/Capstone Project/CS4/CS4.gen/sources_1/bd/top/top_ooc.xdc
