# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Dev/Documents/vivado test/WYWM/Capstone Project/CS4/CS4.srcs/sources_1/bd/top/ip/top_ila_0_0/top_ila_0_0.xci
# IP: The module: 'top_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dev/Documents/vivado test/WYWM/Capstone Project/CS4/CS4.gen/sources_1/bd/top/ip/top_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dev/Documents/vivado test/WYWM/Capstone Project/CS4/CS4.gen/sources_1/bd/top/ip/top_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dev/Documents/vivado test/WYWM/Capstone Project/CS4/CS4.gen/sources_1/bd/top/ip/top_ila_0_0/top_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Dev/Documents/vivado test/WYWM/Capstone Project/CS4/CS4.srcs/sources_1/bd/top/ip/top_ila_0_0/top_ila_0_0.xci
# IP: The module: 'top_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dev/Documents/vivado test/WYWM/Capstone Project/CS4/CS4.gen/sources_1/bd/top/ip/top_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dev/Documents/vivado test/WYWM/Capstone Project/CS4/CS4.gen/sources_1/bd/top/ip/top_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dev/Documents/vivado test/WYWM/Capstone Project/CS4/CS4.gen/sources_1/bd/top/ip/top_ila_0_0/top_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
