# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Dev/Documents/vivado test/WYWM/Capstone Project/CS4/CS4.srcs/sources_1/bd/top/ip/top_blk_mem_gen_1_0/top_blk_mem_gen_1_0.xci
# IP: The module: 'top_blk_mem_gen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dev/Documents/vivado test/WYWM/Capstone Project/CS4/CS4.gen/sources_1/bd/top/ip/top_blk_mem_gen_1_0/top_blk_mem_gen_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_blk_mem_gen_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Dev/Documents/vivado test/WYWM/Capstone Project/CS4/CS4.srcs/sources_1/bd/top/ip/top_blk_mem_gen_1_0/top_blk_mem_gen_1_0.xci
# IP: The module: 'top_blk_mem_gen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dev/Documents/vivado test/WYWM/Capstone Project/CS4/CS4.gen/sources_1/bd/top/ip/top_blk_mem_gen_1_0/top_blk_mem_gen_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_blk_mem_gen_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
