# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Basys3_Master_OV7670.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_clk_wiz_0_0 || ORIG_REF_NAME==top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/top/ip/top_I2C_camera_0_0/top_I2C_camera_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_I2C_camera_0_0 || ORIG_REF_NAME==top_I2C_camera_0_0} -quiet] -quiet

# IP: bd/top/ip/top_I2C_OV7670_MasterCon_0_0/top_I2C_OV7670_MasterCon_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_I2C_OV7670_MasterCon_0_0 || ORIG_REF_NAME==top_I2C_OV7670_MasterCon_0_0} -quiet] -quiet

# IP: bd/top/ip/top_Pixel_Capture_0_0/top_Pixel_Capture_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_Pixel_Capture_0_0 || ORIG_REF_NAME==top_Pixel_Capture_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_1_0/top_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_1_0 || ORIG_REF_NAME==top_xlconstant_1_0} -quiet] -quiet

# IP: bd/top/ip/top_blk_mem_gen_1_0/top_blk_mem_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_blk_mem_gen_1_0 || ORIG_REF_NAME==top_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/top/ip/top_BRAM_FIFO_Limit_0_0/top_BRAM_FIFO_Limit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_BRAM_FIFO_Limit_0_0 || ORIG_REF_NAME==top_BRAM_FIFO_Limit_0_0} -quiet] -quiet

# IP: bd/top/ip/top_OV7670_QVGA_SIM_0_0/top_OV7670_QVGA_SIM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_OV7670_QVGA_SIM_0_0 || ORIG_REF_NAME==top_OV7670_QVGA_SIM_0_0} -quiet] -quiet

# IP: bd/top/ip/top_VGA_OutputFrame_Colo_0_0/top_VGA_OutputFrame_Colo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_VGA_OutputFrame_Colo_0_0 || ORIG_REF_NAME==top_VGA_OutputFrame_Colo_0_0} -quiet] -quiet

# IP: bd/top/ip/top_BRAM_reader_0_0/top_BRAM_reader_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_BRAM_reader_0_0 || ORIG_REF_NAME==top_BRAM_reader_0_0} -quiet] -quiet

# IP: bd/top/ip/top_debouncer_0_0/top_debouncer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_debouncer_0_0 || ORIG_REF_NAME==top_debouncer_0_0} -quiet] -quiet

# IP: bd/top/ip/top_ila_0_3/top_ila_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ila_0_3 || ORIG_REF_NAME==top_ila_0_3} -quiet] -quiet

# XDC: e:/FPGA/VHDL/Lab Training/I2C/I2C01/I2C01.gen/sources_1/bd/top/top_ooc.xdc
